export type WorkCategory = "Design" | "Motion" | "Digital" | "Growth";

export type WorkItem = {
  slug: string;
  navLabel: string;
  title: string;
  eyebrow: string;
  category: WorkCategory;
  summary: string;
  intro: string;
  sourceUrl: string;
  heroImage: string;
  imageAlt: string;
  gallery: { src: string; alt: string }[];
  capabilities: string[];
  process: string[];
  proof: string[];
  tools: string[];
};

const asset = (path: string) => `https://www.alvinjampazar.com${path}`;
const localAsset = (path: string) => `${process.env.NEXT_PUBLIC_BASE_PATH ?? ""}${path}`;

export const workItems: WorkItem[] = [
  {
    slug: "graphic-design",
    navLabel: "Graphic Design",
    title: "Graphic Design & Marketing",
    eyebrow: "Visual systems that sell",
    category: "Design",
    summary: "High-impact print and digital assets built to earn attention, establish trust, and move audiences to action.",
    intro: "I combine senior-level art direction with hands-on production knowledge, carrying an idea from creative strategy through pixel-perfect execution and print-ready delivery. The result is a coherent visual system that works from a business card to a billboard.",
    sourceUrl: "https://www.alvinjampazar.com/services/graphic",
    heroImage: asset("/assets/graphic-hero-BtcbrIkk.jpg"),
    imageAlt: "Graphic design and marketing work by Alvin Jampazar",
    gallery: [
      { src: asset("/assets/graphic-rollup-BSKjJPbx.jpg"), alt: "Roll-up banner design" },
      { src: asset("/assets/graphic-businesscard-BF9lqMBf.jpg"), alt: "Premium business card design" },
      { src: asset("/assets/graphic-presentation-DgKJQJM1.jpg"), alt: "Presentation design" },
    ],
    capabilities: ["Campaign key visuals", "Print & large-format design", "Pitch decks & company profiles", "Social and display advertising"],
    process: ["Discover the brand, audience, and objective", "Build concepts, moodboards, and type systems", "Refine with precise production craft", "Deliver organized digital and print-ready files"],
    proof: ["12+ years across UAE creative teams", "Government, corporate, fintech, and technology sectors", "Deep knowledge of production and large-format print"],
    tools: ["Photoshop", "Illustrator", "InDesign", "Acrobat"],
  },
  {
    slug: "ai-specialist",
    navLabel: "AI Specialist",
    title: "AI Creative & Marketing Specialist",
    eyebrow: "Intelligence with creative direction",
    category: "Digital",
    summary: "AI-assisted campaigns, creative production, automation, and analytics translated into practical business growth.",
    intro: "I bridge creative leadership and applied AI: shaping campaign strategy, building content systems, automating repetitive production, and using performance signals to refine the next decision. AI accelerates the work; human judgment protects the brand.",
    sourceUrl: "https://www.alvinjampazar.com/services",
    heroImage: asset("/assets/ai-hero-BK_YwoeZ.jpg"),
    imageAlt: "AI creative production and marketing systems",
    gallery: [
      { src: localAsset("/og.png"), alt: "Alvin Jampazar graphic design and AI systems" },
      { src: asset("/assets/thumb-lambo-kgW4j-sH.png"), alt: "AI cinematic video project" },
    ],
    capabilities: ["AI campaign strategy", "Content personalization", "Creative workflow automation", "Performance analysis & optimization"],
    process: ["Map the business objective and audience", "Design the prompt, content, and automation system", "Produce and quality-control each asset", "Measure, learn, and scale what performs"],
    proof: ["AI-powered marketing leadership", "Custom AI platforms and creative tools", "Image, video, web, and campaign workflows"],
    tools: ["ChatGPT", "Midjourney", "Runway", "Kling AI", "Sora"],
  },
  {
    slug: "motion-design",
    navLabel: "Motion Design",
    title: "Motion Design",
    eyebrow: "Every frame has a job",
    category: "Motion",
    summary: "Kinetic typography, logo reveals, product sequences, and branded motion crafted with rhythm and intent.",
    intro: "My motion work brings graphic-design discipline into time. I plan the narrative, build strong style frames, control timing and easing, and finish with sound-aware polish for broadcast, web, presentation, and social formats.",
    sourceUrl: "https://www.alvinjampazar.com/portfolio?category=motion",
    heroImage: asset("/assets/motion-hero-FiOQ30qv.jpg"),
    imageAlt: "Motion graphics and animation work",
    gallery: [
      { src: asset("/assets/social-motion-thumb-vMxpGkmU.jpg"), alt: "Social media motion pack" },
      { src: asset("/assets/brand-reveal-thumb-DsTWz9eb.jpg"), alt: "Corporate brand reveal" },
      { src: asset("/assets/typography-thumb-CJ50wuyy.jpg"), alt: "Kinetic typography reel" },
    ],
    capabilities: ["Kinetic typography", "Logo & brand reveals", "Social motion systems", "Visual effects & compositing"],
    process: ["Clarify message and creative direction", "Storyboard timing and transitions", "Build and animate production assets", "Polish sound, color, and final exports"],
    proof: ["10+ years of After Effects practice", "2D and 3D integration", "Platform-ready output up to 4K"],
    tools: ["After Effects", "Illustrator", "Cinema 4D", "Premiere Pro"],
  },
  {
    slug: "2d-animation",
    navLabel: "2D Animation",
    title: "2D Animation",
    eyebrow: "Stories drawn into motion",
    category: "Motion",
    summary: "Expressive explainers, character animation, and educational content designed to make complex ideas memorable.",
    intro: "I develop 2D animation from the message outward: concept, storyboard, illustrated assets, rigging or frame-by-frame movement, sound synchronization, and multi-format delivery. Personality and clarity lead every decision.",
    sourceUrl: "https://www.alvinjampazar.com/services/2d-animation",
    heroImage: asset("/assets/animation2d-hero-96_4n-4w.jpg"),
    imageAlt: "2D character animation and storyboard",
    gallery: [
      { src: asset("/assets/infographic-thumb-ia1MLmRn.jpg"), alt: "Infographic explainer animation" },
      { src: asset("/assets/social-motion-thumb-vMxpGkmU.jpg"), alt: "Animated social content" },
    ],
    capabilities: ["Explainer videos", "Character animation", "Infographic & whiteboard motion", "Social animated content"],
    process: ["Define story and visual direction", "Illustrate and storyboard", "Animate with deliberate pacing", "Sync sound and deliver every format"],
    proof: ["9+ years in 2D and motion", "Brand, education, and presentation storytelling", "Source-file and multi-format delivery"],
    tools: ["After Effects", "Illustrator", "Adobe Animate", "Audition"],
  },
  {
    slug: "3d-animation",
    navLabel: "3D Animation",
    title: "3D Animation & Visualization",
    eyebrow: "Depth, light, and cinematic movement",
    category: "Motion",
    summary: "Photoreal product visuals, architectural walkthroughs, and cinematic 3D sequences with polished compositing.",
    intro: "I build the full 3D journey: modeling, materials, lighting, camera direction, animation, rendering, and After Effects finishing. The work balances technical precision with a strong sense of atmosphere and brand storytelling.",
    sourceUrl: "https://www.alvinjampazar.com/services/3d-animation",
    heroImage: asset("/assets/animation3d-hero-D5TfA_EP.jpg"),
    imageAlt: "3D animation and visualization",
    gallery: [
      { src: asset("/assets/3r-realestate-thumb-D131lmrs.jpg"), alt: "3R Real Estate architectural walkthrough" },
      { src: asset("/assets/natures-grove-thumb-0d-gWdwT.jpg"), alt: "Landscape visualization" },
      { src: asset("/assets/spring-wings-thumb-B7muEMH0.jpg"), alt: "3D product animation" },
    ],
    capabilities: ["Architectural walkthroughs", "Product visualization", "3D brand reveals", "Interior & exterior rendering"],
    process: ["Model and stage the scene", "Create materials, lighting, and environment", "Animate camera and key elements", "Render and composite the final sequence"],
    proof: ["Real estate, environment, and product projects", "Cinematic camera and lighting craft", "AI-enhanced compositing workflow"],
    tools: ["Cinema 4D", "Blender", "Lumion", "After Effects"],
  },
  {
    slug: "web-developer",
    navLabel: "Web Developer",
    title: "Web Design & Development",
    eyebrow: "Live products, not static mockups",
    category: "Digital",
    summary: "Responsive, SEO-aware websites and landing pages engineered for clarity, trust, speed, and conversion.",
    intro: "I combine UX thinking, visual design, and practical front-end implementation to ship websites that work in the real world. From information architecture and responsive layouts to forms, light custom code, SEO, and launch support, I stay close to the full product.",
    sourceUrl: "https://www.alvinjampazar.com/client-projects",
    heroImage: localAsset("/skill-web-developer.png"),
    imageAlt: "Black and maroon web development system with responsive interface architecture",
    gallery: [
      { src: localAsset("/skill-web-developer.png"), alt: "Web development workspace and modular responsive layouts" },
      { src: "https://www.alcon-online.site/images/feature-brain.webp", alt: "Alcon AI-accelerated creative platform" },
    ],
    capabilities: ["Responsive websites", "Conversion landing pages", "Webflow implementation", "SEO & performance refinement"],
    process: ["Define users, content, and conversion path", "Wireframe the information architecture", "Design and build responsive pages", "Test, optimize, and launch cleanly"],
    proof: ["9+ live client websites", "Projects for ITSEC, SecureVisa, Alcon, UHUD, and more", "Fast, mobile-first, lead-focused delivery"],
    tools: ["Webflow", "HTML/CSS", "Visual Studio Code", "AI coding tools"],
  },
  {
    slug: "ui-ux",
    navLabel: "UI/UX",
    title: "UI/UX Product Design",
    eyebrow: "Interfaces people want to use",
    category: "Digital",
    summary: "Research-led, responsive product experiences with clear flows, scalable systems, and pixel-perfect handoff.",
    intro: "I turn product goals into intuitive journeys across fintech, e-commerce, food tech, retail, and SaaS. Research, wireframes, prototypes, design systems, micro-interactions, and usability feedback stay connected from first idea to developer handoff.",
    sourceUrl: "https://www.alvinjampazar.com/portfolio?category=uiux",
    heroImage: asset("/assets/hero-uiux-DEo5cuXO.jpg"),
    imageAlt: "Cinematic layered UI and UX screens",
    gallery: [
      { src: localAsset("/og.png"), alt: "Editorial digital systems artwork" },
      { src: asset("/assets/ai-hero-BK_YwoeZ.jpg"), alt: "AI-enabled digital experience" },
    ],
    capabilities: ["User research & strategy", "Wireframes & prototypes", "Design systems", "Responsive & interaction design"],
    process: ["Research users, market, and business goals", "Map flows and wireframe the experience", "Design the system and key screens", "Prototype, test, and refine"],
    proof: ["Fintech, e-commerce, retail, and platform concepts", "Figma-ready developer specifications", "Conversion and usability focus"],
    tools: ["Figma", "Adobe XD", "Webflow", "Photoshop"],
  },
  {
    slug: "photographer",
    navLabel: "Photographer",
    title: "Professional Photography",
    eyebrow: "Capture. Compose. Communicate.",
    category: "Design",
    summary: "Professional wedding, portrait, food, product, and lifestyle photography with meticulous post-production.",
    intro: "My photography is grounded in storytelling, light, and composition. I plan each shoot around the brand or moment, then deliver carefully selected, retouched, and color-graded imagery ready for web, social, campaigns, and print.",
    sourceUrl: "https://www.alvinjampazar.com/portfolio?category=photography",
    heroImage: localAsset("/skill-photography.png"),
    imageAlt: "Professional camera and editorial photography still life in black and maroon",
    gallery: [
      { src: localAsset("/skill-photography.png"), alt: "Editorial photography equipment and curated contact sheets" },
      { src: asset("/assets/wedding-6-CmUUAgJX.jpg"), alt: "Cinematic wedding photography" },
      { src: "https://cdn.prod.website-files.com/65c8be800b7b07d9ce6ff6e1/65fe00aeeba566605419d70a_D-3.jpg", alt: "Fine dining food photography" },
    ],
    capabilities: ["Wedding & portrait photography", "Product & food photography", "Events & lifestyle", "Retouching & color grading"],
    process: ["Align on story and visual references", "Scout, schedule, and plan the light", "Direct and capture the session", "Select, retouch, grade, and deliver"],
    proof: ["Brand and personal storytelling", "Print and digital-ready resolution", "Consistent color-managed finishing"],
    tools: ["Professional camera systems", "Lightroom", "Photoshop", "Premiere Pro"],
  },
  {
    slug: "videography",
    navLabel: "Videography",
    title: "Videography & Production",
    eyebrow: "Shoot with the edit in mind",
    category: "Motion",
    summary: "Cinematic brand films, events, weddings, and promotional content captured with purposeful direction.",
    intro: "I plan, shoot, and shape video as one connected process. Strong shot lists and on-set composition give the edit better material; careful pacing, sound, and color turn that material into a story with lasting brand value.",
    sourceUrl: "https://www.alvinjampazar.com/services/video",
    heroImage: asset("/assets/video-hero-IskuS3oP.jpg"),
    imageAlt: "Professional videography production",
    gallery: [
      { src: asset("/assets/wedding-thumb-Dvcc0Kg8.jpg"), alt: "Cinematic wedding film" },
      { src: asset("/assets/event1-thumb-Cv63OgG_.jpg"), alt: "Corporate event coverage" },
      { src: asset("/assets/ramp-thumb-CWxe82_S.jpg"), alt: "Fashion runway film" },
    ],
    capabilities: ["Corporate & event films", "Promotional video", "Wedding storytelling", "Behind-the-scenes content"],
    process: ["Plan script, story, and shot list", "Capture with cinema-grade technique", "Edit, grade, and design sound", "Deliver masters and platform formats"],
    proof: ["Creative direction through final export", "Cinematic and documentary styles", "Marketing-ready deliverables"],
    tools: ["Camera & lighting systems", "Premiere Pro", "After Effects", "Audition"],
  },
  {
    slug: "photo-video-editing",
    navLabel: "Photo & Video Editing",
    title: "Photo & Video Editing",
    eyebrow: "The finish changes everything",
    category: "Motion",
    summary: "Precision retouching and post-production that turns raw footage and imagery into cohesive, platform-ready stories.",
    intro: "I bring a designer's eye to every edit: composition, rhythm, typography, transitions, skin and product retouching, tonal balance, and final color. Each asset is finished for its real destination rather than exported as a one-size-fits-all file.",
    sourceUrl: "https://www.alvinjampazar.com/portfolio?category=photography",
    heroImage: asset("/assets/editing-hero-B61XNh7T.jpg"),
    imageAlt: "Professional video editing and post-production",
    gallery: [
      { src: asset("/assets/ramp-thumb-CWxe82_S.jpg"), alt: "Cinematic editing and color work" },
      { src: asset("/assets/wedding-3-C8NzDak1.jpg"), alt: "Professional portrait retouching" },
    ],
    capabilities: ["Cinematic editing", "Photo retouching", "Color correction & grading", "Sound, captions, and format optimization"],
    process: ["Review and organize source media", "Build the narrative or visual treatment", "Refine pace, tone, and transitions", "Finish color, sound, and platform exports"],
    proof: ["Frame-precise post-production", "Cinematic, social, and corporate styles", "Multi-platform delivery"],
    tools: ["Premiere Pro", "After Effects", "Photoshop", "Lightroom"],
  },
  {
    slug: "social-media-management",
    navLabel: "Social Media",
    title: "Social Media Management",
    eyebrow: "A brand that shows up consistently",
    category: "Growth",
    summary: "Strategy, content systems, design, community management, and optimization for an always-on social presence.",
    intro: "I connect content planning and visual craft with the daily discipline of publishing, listening, and improving. Content pillars, calendars, campaign assets, copy, and performance reporting work together to grow a recognizable brand and engaged audience.",
    sourceUrl: "https://www.alvinjampazar.com/services/social",
    heroImage: asset("/assets/social-hero-CNTVfSvt.jpg"),
    imageAlt: "Social media content design and management",
    gallery: [
      { src: asset("/assets/carousel-a-Tcj1VvMc.jpg"), alt: "SecureVisa connected carousel" },
      { src: asset("/assets/nexus-otc-01-CvCmkpZq.jpg"), alt: "Nexus Crypto social campaign" },
      { src: asset("/assets/gcgra-gold-C0lRcSQ-.jpg"), alt: "Gaming regulatory social post" },
    ],
    capabilities: ["Content strategy & calendars", "Post design & copy", "Community management", "Reporting & paid campaigns"],
    process: ["Audit brand, audience, and competitors", "Define pillars and publishing rhythm", "Create and distribute platform-native content", "Engage, report, and optimize"],
    proof: ["Fintech, cybersecurity, gaming, and consultancy work", "Connected carousel storytelling", "Design and performance under one lead"],
    tools: ["Meta Ads Manager", "Google Ads", "Adobe Suite", "Analytics tools"],
  },
  {
    slug: "platforms",
    navLabel: "Platforms",
    title: "Digital Platform Builder",
    eyebrow: "From concept to live product",
    category: "Digital",
    summary: "AI-powered tools, SaaS products, and community platforms designed, developed, and deployed end-to-end.",
    intro: "I treat platforms as complete systems: audience need, product structure, UI language, build workflow, launch, and continued refinement. My portfolio spans creative AI, design systems, business operations, agriculture, community, and Web3 products.",
    sourceUrl: "https://www.alvinjampazar.com/digital-platforms",
    heroImage: localAsset("/skill-platforms.png"),
    imageAlt: "Connected modular digital platform ecosystem in black and maroon",
    gallery: [
      { src: localAsset("/skill-platforms.png"), alt: "Interconnected product modules and platform architecture" },
      { src: asset("/assets/ai-hero-BK_YwoeZ.jpg"), alt: "AI platform and automation" },
    ],
    capabilities: ["Product strategy & UX", "AI-assisted platform development", "SaaS & community products", "Launch and iteration"],
    process: ["Validate the problem and users", "Define architecture and core journeys", "Design and build the product system", "Launch, learn, and evolve"],
    proof: ["9+ platforms built", "UIForge, Alvin~AI, BuildFlow, Pixela, ForgeSuite, and more", "Full-stack thinking with creative direction"],
    tools: ["Figma", "AI development tools", "Web platforms", "Analytics"],
  },
  {
    slug: "brand-identity",
    navLabel: "Brand Identity",
    title: "Brand Identity & Guidelines",
    eyebrow: "Recognition, built deliberately",
    category: "Design",
    summary: "Complete identity systems that align strategy, logo, typography, color, imagery, and real-world brand touchpoints.",
    intro: "A brand is not a logo file; it is a repeatable system of decisions. I uncover the positioning, establish a distinctive visual language, test it across real applications, and document the rules so teams can build recognition without losing consistency.",
    sourceUrl: "https://www.alvinjampazar.com/services/branding",
    heroImage: asset("/assets/branding-hero-DDTPXTbQ.jpg"),
    imageAlt: "Brand identity and visual design system",
    gallery: [
      { src: asset("/assets/branding-identity-DugmWTtw.jpg"), alt: "Full brand identity system" },
      { src: asset("/assets/branding-packaging-Bic0j7zL.jpg"), alt: "Brand packaging design" },
      { src: asset("/assets/branding-businesscard-CdhA-hBo.jpg"), alt: "Premium business card identity" },
    ],
    capabilities: ["Logo systems", "Visual identity direction", "Brand collateral", "Guideline documentation"],
    process: ["Discover the vision, audience, and market", "Position the brand and define its voice", "Design, test, and refine the identity", "Deliver the system and launch toolkit"],
    proof: ["150+ brands served", "Corporate, public, technology, and consumer sectors", "Digital and print production expertise"],
    tools: ["Illustrator", "Photoshop", "InDesign", "Figma"],
  },
  {
    slug: "ai-video",
    navLabel: "AI Video",
    title: "AI Video & Storyboards",
    eyebrow: "From a still image to a living story",
    category: "Digital",
    summary: "Cinematic image-to-video production, AI storyboards, and scalable content systems with professional creative control.",
    intro: "I turn a visual concept into a structured storyboard, then direct generative AI through scenes, camera moves, transitions, and motion before adding professional post-production. The workflow makes ambitious video more agile without sacrificing narrative craft.",
    sourceUrl: "https://www.alvinjampazar.com/services/ai",
    heroImage: localAsset("/skill-ai-video.png"),
    imageAlt: "Cinematic AI video storyboards, camera paths, and editing timeline",
    gallery: [
      { src: localAsset("/skill-ai-video.png"), alt: "AI storyboard frames transforming into cinematic motion" },
      { src: asset("/assets/thumb-uae-flag-day-CphVmAGF.jpg"), alt: "UAE Flag Day AI video" },
      { src: asset("/assets/ai-video-thumb-2-DCcITVuV.jpg"), alt: "AI cinematic storyboard video" },
    ],
    capabilities: ["AI storyboard creation", "Image-to-video generation", "Cinematic AI production", "Content variations & localization"],
    process: ["Define brand, audience, and creative goal", "Build a scene-by-scene storyboard", "Generate and direct cinematic motion", "Edit, grade, and optimize every output"],
    proof: ["Single-image to multi-scene workflows", "Brand, social, and campaign applications", "Professional post-production finish"],
    tools: ["Runway", "Kling AI", "Midjourney", "After Effects"],
  },
];

export const workBySlug = Object.fromEntries(workItems.map((item) => [item.slug, item]));

export const experience = [
  {
    role: "Marketing Manager, Senior Designer & AI Specialist",
    company: "SecureVisa Group / ITSEC Cybersecurity",
    place: "Dubai, UAE",
    detail: "Leading integrated marketing, brand identity, websites, UI/UX, motion, AI campaigns, and performance optimization across consultancy and cybersecurity brands.",
  },
  {
    role: "Senior Graphic Designer & Photographer/Videographer",
    company: "Cabilo Advertising",
    place: "Dubai, UAE",
    detail: "Expanded a senior design practice into full-service creative direction, campaign photography, videography, editing, and advanced animation.",
  },
  {
    role: "Senior Graphic Designer, 3D Artist & UI/UX Designer",
    company: "Excel Pixel",
    place: "Abu Dhabi, UAE",
    detail: "Delivered senior-level graphic design, 3D visualization, UI/UX, and client-facing creative direction for a diverse portfolio.",
  },
  {
    role: "Creative Foundation",
    company: "Target Car Care · Molten Me · Afaneen · Diamond Lines",
    place: "Abu Dhabi, UAE",
    detail: "Built deep production experience across large-format print, vehicle and marine graphics, social media, brand identity, and 2D animation.",
  },
];
